# Generated by Django 3.2.8 on 2021-10-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='couses/images', verbose_name='Imagem'),
        ),
    ]
